import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full bg-gradient-to-r from-blue-600 to-blue-400 border-b shadow-md mb-8">
          <div className="max-w-5xl mx-auto flex items-center justify-between p-4">
            <Link
              href="/"
              className="text-2xl font-extrabold text-white tracking-wide drop-shadow-lg hover:text-yellow-200 transition"
            >
              Referral Hub
            </Link>
            <div className="flex gap-4 items-center">
              <Link
                href="/about"
                className="hover:underline text-white hover:text-yellow-200 transition"
              >
                About
              </Link>
              <Link
                href="/"
                className="hover:underline text-white hover:text-yellow-200 transition"
              >
                Dashboard
              </Link>
              <Link
                href="/submit"
                className="hover:underline text-white hover:text-yellow-200 transition"
              >
                Submit
              </Link>
              <Link
                href="/profile"
                className="hover:underline text-white hover:text-yellow-200 transition"
              >
                Profile
              </Link>
              <Link
                href="/logout"
                className="flex items-center gap-1 bg-white/20 text-white font-semibold px-4 py-1 rounded-full shadow hover:bg-white/40 hover:text-blue-800 transition border border-white/30"
                style={{ backdropFilter: 'blur(2px)' }}
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a2 2 0 01-2 2H7a2 2 0 01-2-2V7a2 2 0 012-2h4a2 2 0 012 2v1" /></svg>
                Login / Logout
              </Link>
            </div>
          </div>
        </nav>
        <div className="transition-opacity duration-300 ease-in-out opacity-100">
          {children}
        </div>
      </body>
    </html>
  );
}
